apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: jenkinsseedjobs.operator-service.com
spec:
  group: operator-service.com
  names:
    kind: JenkinsSeedJob
    listKind: JenkinsSeedJobList
    plural: jenkinsseedjobs
    singular: jenkinsseedjob
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: JenkinsSeedJob is the Schema for the jenkinsseedjobs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: JenkinsSeedJobSpec defines the desired state of JenkinsSeedJob.
              It allows to create Seed Jobs which are executed on Jenkins startup.
            properties:
              agentRef:
                description: AgentRef is reference to agent
                properties:
                  name:
                    description: Name is unique within a namespace to reference a
                      secret resource.
                    type: string
                  namespace:
                    description: Namespace defines the space within which the secret
                      name must be unique.
                    type: string
                required:
                - name
                - namespace
                type: object
              description:
                description: Description is the description of the seed job
                type: string
              repository:
                description: Repository is the place where seed job definitions are
                  defined
                properties:
                  branch:
                    description: Branch is the repository branch where seed job definitions
                      are stored
                    type: string
                  credentialID:
                    description: CredentialID is the Kubernetes secret name which
                      stores repository access credentials
                    type: string
                  credentialType:
                    description: CredentialType is the https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/
                      credential type
                    type: string
                  targets:
                    description: Targets is the path from repository root where seed
                      job definitions are stored
                    type: string
                  url:
                    description: URL is the repository access URL. Can be SSH or HTTPS.
                    type: string
                type: object
              settings:
                description: Settings configures the Git specific properties
                properties:
                  additionalClasspath:
                    description: AdditionalClasspath is setting for Job DSL API plugin
                      to set Additional Classpath
                    type: string
                  failOnMissingPlugin:
                    description: FailOnMissingPlugin is setting for Job DSL API plugin
                      that fails job if required plugin is missing
                    type: boolean
                  ignoreMissingFiles:
                    description: IgnoreMissingFiles is setting for Job DSL API plugin
                      to ignore files that are missing
                    type: boolean
                  unstableOnDeprecation:
                    description: UnstableOnDeprecation is setting for Job DSL API
                      plugin that sets build status as unstable if build using deprecated
                      features
                    type: boolean
                type: object
              triggers:
                description: Triggers are used for Git servers web hooks
                properties:
                  bitbucket:
                    description: BitbucketTrigger is used for Bitbucket web hooks
                    properties:
                      push:
                        description: Push indicates that Jenkins seed job is executed
                          on every detected push to corresponding Git repository
                        type: boolean
                    required:
                    - push
                    type: object
                  buildPeriodically:
                    description: BuildPeriodically is used for scheduled timer trigger
                    type: string
                  github:
                    description: GitHubTrigger is used for GitHub web hooks
                    properties:
                      push:
                        description: Push indicates that Jenkins seed job is executed
                          on every detected push to corresponding Git repository
                        type: boolean
                    required:
                    - push
                    type: object
                  pollSCM:
                    description: PollSCM is setting for polling changes in SCM
                    type: string
                type: object
            type: object
          status:
            description: JenkinsSeedJobStatus defines the observed state of JenkinsSeedJob
            properties:
              conditions:
                description: Conditions contains JenkinsSeedJob statuses
                items:
                  properties:
                    lastProbeTime:
                      description: Last time we probed the condition.
                      format: date-time
                      type: string
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: 'Status is the status of the condition. Can be
                        True, False, Unknown. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions'
                      type: string
                    type:
                      description: 'Type is the type of the condition. More info:
                        https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions'
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              hash:
                description: Hash contains hash computed when running this script
                type: string
              operatorVersion:
                description: OperatorVersion is the operator version which manages
                  this CR
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
